### ISSUE TITLE
Body parser is not tolerant of whitespace??

### ISSUE THREAD

**Issue by grncdr** [CircleCI-Public/api-preview-docs#66] opened 2019-10-23 08:17 UTC
The docs have this example request:

```sh
curl -u ${CIRCLECI_TOKEN}: -X POST --header "Content-Type: application/json" -d '{
  "branch": "dev"
}' https://circleci.com/api/v2/project/${project_slug}/pipeline
```

However, whenever I include "branch" in my request body (even just `{"branch": "master"}`) I get a response that says `{"message": "Invalid JSON body."}`.

What I _really_ want to do is pass a git commit hash, to trigger a parameterized pipeline for a specific commit, is that intended to be supported?

**Comment by grncdr** [comment] 2019-10-23 08:53
A bit more debugging has revealed that I seem to get different results _depending on whitespace in the JSON body_. `{"branch":"master"}` works while `{"branch": "master"}` fails.

**Comment by gordonsyme** [comment] 2019-10-23 09:41
Hi there,

I'm not able to reproduce this, would you mind contacting our support folks so you can provide specifics of your repo? That'll give me somewhere to start investigating from.

Also, our JSON parser won't accept much of the [unicode whitespace set (U+0085 and above)](https://en.wikipedia.org/wiki/Whitespace_character), would you mind double checking that there isn't any of that in the JSON body you are providing?

Thanks

**Comment by gordonsyme** [comment] 2019-10-31 14:27
Gonna close this now, please do reach out to support if you're still having trouble.

**Closed by gordonsyme** 2019-10-31 14:27 UTC
